#!/usr/bin/env python3
# Copyright (c) 2026 Michael J. Read. All rights reserved.
# SPDX-License-Identifier: BUSL-1.1
"""Compose deployment from a manifest that references network + product patterns.

Reads a manifest.yaml, resolves pattern references, applies ID prefixes,
merges patterns into composed system.yaml + networks.yaml + deployment.yaml.

Usage:
    python tools/compose.py deployments/prod-us-east/manifest.yaml
    python tools/compose.py deployments/prod-us-east/manifest.yaml --validate
    python tools/compose.py deployments/prod-us-east/manifest.yaml --dry-run

Output:
    Writes composed files alongside the manifest:
      - networks.yaml   (composed network topology)
      - system.yaml     (composed system architecture)
      - deployment.yaml  (zone placements)
"""

import argparse
import copy
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

KEBAB_CASE_RE = re.compile(r'^[a-z][a-z0-9]*(-[a-z0-9]+)*$')
PROJECT_ROOT = Path(__file__).parent.parent
PATTERNS_DIR = PROJECT_ROOT / "patterns"

GENERATED_HEADER = (
    "# GENERATED by compose.py from {manifest_path}\n"
    "# DO NOT EDIT — modify the manifest or source patterns instead.\n"
    "# Generated: {timestamp}\n"
)


def _find_pattern_dir(pattern_ref: str, pattern_type: str) -> Path | None:
    """Locate a pattern directory by ID within the patterns tree."""
    subdir = "networks" if pattern_type == "network" else "products"
    base = PATTERNS_DIR / subdir
    # Search recursively for a directory matching the pattern_ref
    for d in base.rglob("*"):
        if d.is_dir() and d.name == pattern_ref:
            meta_path = d / "pattern.meta.yaml"
            if meta_path.exists():
                return d
    return None


def _prefix_id(original: str, prefix: str) -> str:
    """Apply prefix to an ID: prefix-original."""
    return f"{prefix}-{original}"


def _prefix_ids_in_list(entities: list[dict], prefix: str, id_field: str = "id",
                        ref_fields: list[str] | None = None) -> list[dict]:
    """Deep-copy a list of entities and prefix their IDs and reference fields."""
    result = []
    for entity in entities:
        e = copy.deepcopy(entity)
        if id_field in e:
            e[id_field] = _prefix_id(e[id_field], prefix)
        for field in (ref_fields or []):
            if field in e and isinstance(e[field], str):
                e[field] = _prefix_id(e[field], prefix)
            elif field in e and isinstance(e[field], list):
                e[field] = [_prefix_id(v, prefix) for v in e[field]]
        result.append(e)
    return result


def _apply_overrides(entities: list[dict], overrides: dict, prefix: str) -> list[dict]:
    """Apply per-entity field overrides from the manifest."""
    if not overrides:
        return entities
    for entity in entities:
        # Check against both original and prefixed ID
        original_id = entity.get("id", "")
        # Try matching override by original (unprefixed) ID
        for override_key, override_vals in overrides.items():
            prefixed_key = _prefix_id(override_key, prefix)
            if original_id == prefixed_key and isinstance(override_vals, dict):
                entity.update(override_vals)
    return entities


def _load_pattern_contexts(pattern_dir: Path, prefix: str) -> tuple[list[dict], list[dict]]:
    """Load and prefix contexts from a pattern's contexts/_context.yaml if it exists."""
    context_path = pattern_dir / "contexts" / "_context.yaml"
    if not context_path.exists():
        return [], []

    with open(context_path) as f:
        ctx_data = yaml.safe_load(f) or {}

    contexts = _prefix_ids_in_list(
        ctx_data.get("contexts", []), prefix
    )
    context_rels = _prefix_ids_in_list(
        ctx_data.get("context_relationships", []), prefix,
        ref_fields=["source_context", "target_context"]
    )
    return contexts, context_rels


def compose_network(manifest: dict) -> dict:
    """Compose the network portion from the manifest's network pattern."""
    net_spec = manifest["network"]
    pattern_ref = net_spec["pattern_ref"]
    prefix = net_spec["id_prefix"]
    overrides = net_spec.get("overrides", {})

    pattern_dir = _find_pattern_dir(pattern_ref, "network")
    if not pattern_dir:
        raise FileNotFoundError(f"Network pattern '{pattern_ref}' not found under patterns/networks/")

    meta_path = pattern_dir / "pattern.meta.yaml"
    networks_path = pattern_dir / "networks.yaml"
    if not networks_path.exists():
        raise FileNotFoundError(f"Network pattern '{pattern_ref}' missing networks.yaml")

    # Version check
    with open(meta_path) as f:
        meta = yaml.safe_load(f)
    pinned_version = net_spec.get("version")
    if pinned_version and meta["pattern"]["version"] != pinned_version:
        raise ValueError(
            f"Network pattern '{pattern_ref}' version mismatch: "
            f"manifest pins {pinned_version}, pattern has {meta['pattern']['version']}"
        )

    with open(networks_path) as f:
        net_data = yaml.safe_load(f)

    # Prefix zone IDs
    zones = _prefix_ids_in_list(
        net_data.get("network_zones", []), prefix,
        ref_fields=["allowed_ingress_zones", "allowed_egress_zones"]
    )

    # Prefix infrastructure resource IDs and zone_id refs
    resources = _prefix_ids_in_list(
        net_data.get("infrastructure_resources", []), prefix,
        ref_fields=["zone_id"]
    )

    # Apply overrides
    zones = _apply_overrides(zones, overrides, prefix)
    resources = _apply_overrides(resources, overrides, prefix)

    # Load network pattern contexts
    net_contexts, net_ctx_rels = _load_pattern_contexts(pattern_dir, prefix)

    result = {
        "network_zones": zones,
        "infrastructure_resources": resources,
    }
    if net_contexts:
        result["_contexts"] = net_contexts
    if net_ctx_rels:
        result["_context_relationships"] = net_ctx_rels

    return result


def compose_system(manifest: dict) -> dict:
    """Compose the system portion from all product patterns in the manifest."""
    products = manifest["products"]
    prefixes = [p["id_prefix"] for p in products]

    # Check for duplicate prefixes
    if len(prefixes) != len(set(prefixes)):
        dupes = [p for p in prefixes if prefixes.count(p) > 1]
        raise ValueError(f"Duplicate product id_prefix values: {set(dupes)}")

    all_contexts = []
    all_context_relationships = []
    all_containers = []
    all_components = []
    all_relationships = []
    all_container_relationships = []
    all_external_systems = []
    all_data_entities = []
    all_trust_boundaries = []

    for product_spec in products:
        pattern_ref = product_spec["pattern_ref"]
        prefix = product_spec["id_prefix"]
        overrides = product_spec.get("overrides", {})

        pattern_dir = _find_pattern_dir(pattern_ref, "product")
        if not pattern_dir:
            raise FileNotFoundError(f"Product pattern '{pattern_ref}' not found under patterns/products/")

        meta_path = pattern_dir / "pattern.meta.yaml"
        system_path = pattern_dir / "system.yaml"
        if not system_path.exists():
            raise FileNotFoundError(f"Product pattern '{pattern_ref}' missing system.yaml")

        # Version check
        with open(meta_path) as f:
            meta = yaml.safe_load(f)
        pinned_version = product_spec.get("version")
        if pinned_version and meta["pattern"]["version"] != pinned_version:
            raise ValueError(
                f"Product pattern '{pattern_ref}' version mismatch: "
                f"manifest pins {pinned_version}, pattern has {meta['pattern']['version']}"
            )

        with open(system_path) as f:
            sys_data = yaml.safe_load(f)

        # Contexts — merge _context.yaml (if present) with inline contexts from system.yaml
        # Inline contexts are needed because containers reference them via context_id
        ctx_from_dir, ctx_rels_from_dir = _load_pattern_contexts(pattern_dir, prefix)
        inline_contexts = _prefix_ids_in_list(
            sys_data.get("contexts", []), prefix
        )
        # Merge: start with inline, add any from _context.yaml that aren't duplicates
        inline_ids = {c["id"] for c in inline_contexts if "id" in c}
        contexts = list(inline_contexts)
        for ctx in ctx_from_dir:
            if ctx.get("id") not in inline_ids:
                contexts.append(ctx)
        # Apply context_name override
        if product_spec.get("context_name") and contexts:
            contexts[0]["name"] = product_spec["context_name"]

        # Containers
        containers = _prefix_ids_in_list(
            sys_data.get("containers", []), prefix,
            ref_fields=["context_id"]
        )

        # Components — need to prefix container_id and listener IDs
        components = []
        for comp in sys_data.get("components", []):
            c = copy.deepcopy(comp)
            c["id"] = _prefix_id(c["id"], prefix)
            if "container_id" in c:
                c["container_id"] = _prefix_id(c["container_id"], prefix)
            # Prefix listener IDs
            for listener in c.get("listeners", []):
                listener["id"] = _prefix_id(listener["id"], prefix)
            components.append(c)

        # Component relationships
        relationships = _prefix_ids_in_list(
            sys_data.get("component_relationships", []), prefix,
            ref_fields=["source_component", "target_component", "target_listener_ref"]
        )

        # Container relationships
        ctr_relationships = _prefix_ids_in_list(
            sys_data.get("container_relationships", []), prefix,
            ref_fields=["source_container", "target_container"]
        )

        # External systems, data entities, trust boundaries
        ext_systems = _prefix_ids_in_list(
            sys_data.get("external_systems", []), prefix
        )
        data_ents = _prefix_ids_in_list(
            sys_data.get("data_entities", []), prefix
        )
        trust_bounds = _prefix_ids_in_list(
            sys_data.get("trust_boundaries", []), prefix,
            ref_fields=["source_zone", "target_zone"]
        )

        # Apply overrides
        containers = _apply_overrides(containers, overrides, prefix)
        components = _apply_overrides(components, overrides, prefix)

        all_contexts.extend(contexts)
        all_context_relationships.extend(ctx_rels_from_dir)
        all_containers.extend(containers)
        all_components.extend(components)
        all_relationships.extend(relationships)
        all_container_relationships.extend(ctr_relationships)
        all_external_systems.extend(ext_systems)
        all_data_entities.extend(data_ents)
        all_trust_boundaries.extend(trust_bounds)

    # Add cross-product relationships from manifest
    for rel in manifest.get("cross_product_relationships", []):
        all_relationships.append(copy.deepcopy(rel))

    # Merge network pattern contexts into the system (if any)
    # Network contexts come from compose_network's _contexts key
    # They are injected via compose() after both compose_network and compose_system run

    # Build composed system
    composed = {
        "metadata": {
            "name": manifest["name"],
            "description": manifest.get("description", ""),
            "owner": "composed-deployment",
            "status": manifest.get("status", "proposed"),
        },
        "contexts": all_contexts,
        "containers": all_containers,
        "components": all_components,
        "component_relationships": all_relationships,
    }

    if all_context_relationships:
        composed["context_relationships"] = all_context_relationships
    if all_container_relationships:
        composed["container_relationships"] = all_container_relationships
    if all_external_systems:
        composed["external_systems"] = all_external_systems
    if all_data_entities:
        composed["data_entities"] = all_data_entities
    if all_trust_boundaries:
        composed["trust_boundaries"] = all_trust_boundaries

    return composed


def compose_deployment(manifest: dict) -> dict:
    """Generate deployment YAML from manifest placements."""
    net_prefix = manifest["network"]["id_prefix"]

    deployment = {
        "deployment_metadata": {
            "id": manifest["id"],
            "name": manifest["name"],
            "environment": manifest["environment"],
            "status": manifest.get("status", "proposed"),
        },
    }

    if manifest.get("region"):
        deployment["deployment_metadata"]["region"] = manifest["region"]
    if manifest.get("cloud_provider"):
        deployment["deployment_metadata"]["cloud_provider"] = manifest["cloud_provider"]

    # Build zone placements from manifest
    placements = manifest.get("placements", [])
    if placements:
        # Group placements by zone_ref
        zone_map: dict[str, list[dict]] = {}
        for p in placements:
            zone_ref = p["zone_ref"]
            if zone_ref not in zone_map:
                zone_map[zone_ref] = []
            container_entry: dict = {"container_id": p["container_ref"]}
            for field in ("replicas", "runtime_user", "read_only_filesystem",
                          "resource_limits_set", "network_policy_enforced",
                          "image_signed"):
                if field in p:
                    container_entry[field] = p[field]
            zone_map[zone_ref].append(container_entry)

        deployment["zone_placements"] = [
            {"zone_id": zone_id, "containers": ctrs}
            for zone_id, ctrs in zone_map.items()
        ]

    return deployment


def compose(manifest_path: Path, dry_run: bool = False,
            validate: bool = False) -> dict:
    """Main composition pipeline."""
    with open(manifest_path) as f:
        raw = yaml.safe_load(f)

    manifest = raw.get("manifest")
    if not manifest:
        raise ValueError(f"Manifest file missing top-level 'manifest' key: {manifest_path}")

    # Compose
    networks = compose_network(manifest)
    system = compose_system(manifest)
    deployment = compose_deployment(manifest)

    # Inject network pattern contexts into composed system
    net_contexts = networks.pop("_contexts", [])
    net_ctx_rels = networks.pop("_context_relationships", [])
    if net_contexts:
        system["contexts"] = net_contexts + system.get("contexts", [])
    if net_ctx_rels:
        existing_ctx_rels = system.get("context_relationships", [])
        system["context_relationships"] = net_ctx_rels + existing_ctx_rels

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        rel_manifest = str(manifest_path.relative_to(PROJECT_ROOT))
    except ValueError:
        rel_manifest = str(manifest_path)
    header = GENERATED_HEADER.format(
        manifest_path=rel_manifest,
        timestamp=timestamp,
    )

    output_dir = manifest_path.parent

    result = {
        "valid": True,
        "networks": networks,
        "system": system,
        "deployment": deployment,
        "output_dir": str(output_dir),
        "errors": [],
        "warnings": [],
    }

    # Add context_relationships to composed output if present
    if system.get("context_relationships"):
        pass  # already set above

    if dry_run:
        print(json.dumps({
            "dry_run": True,
            "valid": True,
            "networks_zones_count": len(networks.get("network_zones", [])),
            "networks_resources_count": len(networks.get("infrastructure_resources", [])),
            "system_contexts_count": len(system.get("contexts", [])),
            "system_containers_count": len(system.get("containers", [])),
            "system_components_count": len(system.get("components", [])),
            "system_relationships_count": len(system.get("component_relationships", [])),
            "deployment_placements_count": len(deployment.get("zone_placements", [])),
            "output_dir": str(output_dir),
        }, indent=2))
        return result

    # Write output files
    for fname, data in [("networks.yaml", networks),
                        ("system.yaml", system),
                        ("deployment.yaml", deployment)]:
        out_path = output_dir / fname
        with open(out_path, "w") as f:
            f.write(header)
            yaml.dump(data, f, default_flow_style=False, sort_keys=False,
                      allow_unicode=True)

    # Validate composed output
    if validate:
        try:
            sys.path.insert(0, str(PROJECT_ROOT / "tools"))
            from validate import validate as run_validate
            val_result = run_validate(
                str(output_dir / "system.yaml"),
                str(output_dir / "networks.yaml"),
            )
            result["errors"] = val_result.get("errors", [])
            result["warnings"] = val_result.get("warnings", [])
            result["valid"] = val_result.get("valid", True)
        except Exception as e:
            result["warnings"].append(f"Validation skipped: {e}")

    print(json.dumps({
        "valid": result["valid"],
        "errors": result["errors"],
        "warnings": result["warnings"],
        "files_written": [
            str(output_dir / "networks.yaml"),
            str(output_dir / "system.yaml"),
            str(output_dir / "deployment.yaml"),
        ],
    }, indent=2))

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Compose deployment from manifest + patterns")
    parser.add_argument("manifest", type=Path,
                        help="Path to manifest.yaml")
    parser.add_argument("--validate", action="store_true",
                        help="Validate composed output against schemas")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print composition summary without writing files")
    args = parser.parse_args()

    if not args.manifest.exists():
        print(json.dumps({
            "valid": False,
            "errors": [f"Manifest not found: {args.manifest}"],
        }))
        sys.exit(1)

    try:
        result = compose(args.manifest, dry_run=args.dry_run,
                         validate=args.validate)
        sys.exit(0 if result["valid"] else 1)
    except Exception as e:
        print(json.dumps({
            "valid": False,
            "errors": [str(e)],
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()
