#!/usr/bin/env python3
# Copyright (c) 2026 Michael J. Read. All rights reserved.
# SPDX-License-Identifier: BUSL-1.1
"""Compose deployment from a manifest that references network + product patterns.

Reads a manifest.yaml, resolves pattern references, applies ID prefixes,
merges patterns into composed system.yaml + networks.yaml + deployment.yaml.

Usage:
    python tools/compose.py deployments/prod-us-east/manifest.yaml
    python tools/compose.py deployments/prod-us-east/manifest.yaml --validate
    python tools/compose.py deployments/prod-us-east/manifest.yaml --dry-run

Output:
    Writes composed files alongside the manifest:
      - networks.yaml   (composed network topology)
      - system.yaml     (composed system architecture)
      - deployment.yaml  (zone placements)
"""

import argparse
import copy
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

KEBAB_CASE_RE = re.compile(r'^[a-z][a-z0-9]*(-[a-z0-9]+)*$')
PROJECT_ROOT = Path(__file__).parent.parent
PATTERNS_DIR = PROJECT_ROOT / "patterns"

GENERATED_HEADER = (
    "# GENERATED by compose.py from {manifest_path}\n"
    "# DO NOT EDIT — modify the manifest or source patterns instead.\n"
    "# Generated: {timestamp}\n"
)


def _find_pattern_dir(pattern_ref: str, pattern_type: str) -> Path | None:
    """Locate a pattern directory by ID within the patterns tree."""
    subdir = "networks" if pattern_type == "network" else "products"
    base = PATTERNS_DIR / subdir
    # Search recursively for a directory matching the pattern_ref
    for d in base.rglob("*"):
        if d.is_dir() and d.name == pattern_ref:
            meta_path = d / "pattern.meta.yaml"
            if meta_path.exists():
                return d
    return None


def _prefix_id(original: str, prefix: str) -> str:
    """Apply prefix to an ID: prefix-original."""
    return f"{prefix}-{original}"


def _prefix_ids_in_list(entities: list[dict], prefix: str, id_field: str = "id",
                        ref_fields: list[str] | None = None) -> list[dict]:
    """Deep-copy a list of entities and prefix their IDs and reference fields."""
    result = []
    for entity in entities:
        e = copy.deepcopy(entity)
        if id_field in e:
            e[id_field] = _prefix_id(e[id_field], prefix)
        for field in (ref_fields or []):
            if field in e and isinstance(e[field], str):
                e[field] = _prefix_id(e[field], prefix)
            elif field in e and isinstance(e[field], list):
                e[field] = [_prefix_id(v, prefix) for v in e[field]]
        result.append(e)
    return result


def _apply_overrides(entities: list[dict], overrides: dict, prefix: str) -> list[dict]:
    """Apply per-entity field overrides from the manifest."""
    if not overrides:
        return entities
    for entity in entities:
        # Check against both original and prefixed ID
        original_id = entity.get("id", "")
        # Try matching override by original (unprefixed) ID
        for override_key, override_vals in overrides.items():
            prefixed_key = _prefix_id(override_key, prefix)
            if original_id == prefixed_key and isinstance(override_vals, dict):
                entity.update(override_vals)
    return entities


def _load_pattern_contexts(pattern_dir: Path, prefix: str) -> tuple[list[dict], list[dict]]:
    """Load and prefix contexts from a pattern's contexts/_context.yaml if it exists."""
    context_path = pattern_dir / "contexts" / "_context.yaml"
    if not context_path.exists():
        return [], []

    with open(context_path) as f:
        ctx_data = yaml.safe_load(f) or {}

    contexts = _prefix_ids_in_list(
        ctx_data.get("contexts", []), prefix
    )
    context_rels = _prefix_ids_in_list(
        ctx_data.get("context_relationships", []), prefix,
        ref_fields=["source_context", "target_context"]
    )
    return contexts, context_rels


def _normalize_network_specs(manifest: dict) -> list[dict]:
    """Normalize singular 'network' or plural 'networks' into a list.

    Provides backward compatibility: old manifests with ``network:`` (object)
    are wrapped in a single-element list.  New manifests use ``networks:``
    (array).  Having both is an error.
    """
    has_singular = "network" in manifest
    has_plural = "networks" in manifest
    if has_singular and has_plural:
        raise ValueError(
            "Manifest has both 'network' and 'networks' — use one or the other"
        )
    if has_plural:
        return manifest["networks"]
    if has_singular:
        return [manifest["network"]]
    raise ValueError("Manifest must have either 'network' or 'networks' field")


def _compose_single_network(net_spec: dict) -> dict:
    """Compose one network pattern from a single network spec entry."""
    pattern_ref = net_spec["pattern_ref"]
    prefix = net_spec["id_prefix"]
    overrides = net_spec.get("overrides", {})

    pattern_dir = _find_pattern_dir(pattern_ref, "network")
    if not pattern_dir:
        raise FileNotFoundError(f"Network pattern '{pattern_ref}' not found under patterns/networks/")

    meta_path = pattern_dir / "pattern.meta.yaml"
    networks_path = pattern_dir / "networks.yaml"
    if not networks_path.exists():
        raise FileNotFoundError(f"Network pattern '{pattern_ref}' missing networks.yaml")

    # Version check
    with open(meta_path) as f:
        meta = yaml.safe_load(f)
    pinned_version = net_spec.get("version")
    if pinned_version and meta["pattern"]["version"] != pinned_version:
        raise ValueError(
            f"Network pattern '{pattern_ref}' version mismatch: "
            f"manifest pins {pinned_version}, pattern has {meta['pattern']['version']}"
        )

    with open(networks_path) as f:
        net_data = yaml.safe_load(f)

    # Prefix zone IDs
    zones = _prefix_ids_in_list(
        net_data.get("network_zones", []), prefix,
        ref_fields=["allowed_ingress_zones", "allowed_egress_zones"]
    )

    # Prefix infrastructure resource IDs and zone_id refs
    resources = _prefix_ids_in_list(
        net_data.get("infrastructure_resources", []), prefix,
        ref_fields=["zone_id"]
    )

    # Apply overrides
    zones = _apply_overrides(zones, overrides, prefix)
    resources = _apply_overrides(resources, overrides, prefix)

    # Load network pattern contexts
    net_contexts, net_ctx_rels = _load_pattern_contexts(pattern_dir, prefix)

    # Load optional system.yaml from network pattern (unified patterns)
    system_path = pattern_dir / "system.yaml"
    system_data = None
    if system_path.exists():
        with open(system_path) as f:
            system_data = yaml.safe_load(f) or {}

    result = {
        "network_zones": zones,
        "infrastructure_resources": resources,
    }
    if net_contexts:
        result["_contexts"] = net_contexts
    if net_ctx_rels:
        result["_context_relationships"] = net_ctx_rels
    if system_data:
        result["_system"] = system_data

    return result


def _apply_cross_network_links(all_zones: list[dict],
                                links: list[dict]) -> None:
    """Inject cross_network_links into zone allowed_ingress/egress arrays."""
    zone_map = {z["id"]: z for z in all_zones}
    for link in links:
        src_id = link["source_zone"]
        tgt_id = link["target_zone"]
        direction = link.get("direction", "bidirectional")
        valid_directions = ("egress", "ingress", "bidirectional")
        if direction not in valid_directions:
            raise ValueError(
                f"cross_network_links: invalid direction '{direction}', "
                f"must be one of {valid_directions}"
            )

        if src_id not in zone_map:
            raise ValueError(f"cross_network_links: source_zone '{src_id}' not found")
        if tgt_id not in zone_map:
            raise ValueError(f"cross_network_links: target_zone '{tgt_id}' not found")

        src_zone = zone_map[src_id]
        tgt_zone = zone_map[tgt_id]

        if direction in ("egress", "bidirectional"):
            egress = src_zone.setdefault("allowed_egress_zones", [])
            if tgt_id not in egress:
                egress.append(tgt_id)
        if direction in ("ingress", "bidirectional"):
            ingress = tgt_zone.setdefault("allowed_ingress_zones", [])
            if src_id not in ingress:
                ingress.append(src_id)
        if direction == "bidirectional":
            ingress_src = src_zone.setdefault("allowed_ingress_zones", [])
            if tgt_id not in ingress_src:
                ingress_src.append(tgt_id)
            egress_tgt = tgt_zone.setdefault("allowed_egress_zones", [])
            if src_id not in egress_tgt:
                egress_tgt.append(src_id)


def compose_networks(manifest: dict) -> dict:
    """Compose all network patterns from the manifest into merged zones/resources.

    Supports both singular ``network:`` (backward compat) and plural
    ``networks:`` (multi-network).  Validates globally unique zone IDs
    after prefixing and applies cross_network_links.
    """
    net_specs = _normalize_network_specs(manifest)

    # Check for duplicate prefixes among networks
    prefixes = [s["id_prefix"] for s in net_specs]
    if len(prefixes) != len(set(prefixes)):
        dupes = [p for p in prefixes if prefixes.count(p) > 1]
        raise ValueError(f"Duplicate network id_prefix values: {set(dupes)}")

    all_zones: list[dict] = []
    all_resources: list[dict] = []
    all_contexts: list[dict] = []
    all_ctx_rels: list[dict] = []
    all_system_data: list[tuple[str, dict]] = []  # (prefix, system_data)

    for net_spec in net_specs:
        result = _compose_single_network(net_spec)
        all_zones.extend(result["network_zones"])
        all_resources.extend(result.get("infrastructure_resources", []))
        if "_contexts" in result:
            all_contexts.extend(result["_contexts"])
        if "_context_relationships" in result:
            all_ctx_rels.extend(result["_context_relationships"])
        if "_system" in result:
            all_system_data.append((net_spec["id_prefix"], result["_system"]))

    # Validate globally unique zone IDs
    zone_ids = [z["id"] for z in all_zones]
    if len(zone_ids) != len(set(zone_ids)):
        dupes = [z for z in zone_ids if zone_ids.count(z) > 1]
        raise ValueError(f"Zone ID collision across network patterns: {set(dupes)}")

    # NOTE: cross_network_links are applied later in compose() after product
    # zones have been merged, so they can reference product-contributed zones.

    composed = {
        "network_zones": all_zones,
        "infrastructure_resources": all_resources,
    }
    if all_contexts:
        composed["_contexts"] = all_contexts
    if all_ctx_rels:
        composed["_context_relationships"] = all_ctx_rels
    if all_system_data:
        composed["_network_system_data"] = all_system_data

    return composed


# Keep backward-compat alias
compose_network = compose_networks


def compose_system(manifest: dict) -> dict:
    """Compose the system portion from all product patterns in the manifest."""
    products = manifest["products"]
    prefixes = [p["id_prefix"] for p in products]

    # Check for duplicate prefixes
    if len(prefixes) != len(set(prefixes)):
        dupes = [p for p in prefixes if prefixes.count(p) > 1]
        raise ValueError(f"Duplicate product id_prefix values: {set(dupes)}")

    all_contexts = []
    all_context_relationships = []
    all_containers = []
    all_components = []
    all_relationships = []
    all_container_relationships = []
    all_external_systems = []
    all_data_entities = []
    all_trust_boundaries = []
    all_product_zones = []          # zones from product patterns (unified)
    all_product_resources = []      # infra resources from product patterns

    for product_spec in products:
        pattern_ref = product_spec["pattern_ref"]
        prefix = product_spec["id_prefix"]
        overrides = product_spec.get("overrides", {})

        pattern_dir = _find_pattern_dir(pattern_ref, "product")
        if not pattern_dir:
            raise FileNotFoundError(f"Product pattern '{pattern_ref}' not found under patterns/products/")

        meta_path = pattern_dir / "pattern.meta.yaml"
        system_path = pattern_dir / "system.yaml"
        if not system_path.exists():
            raise FileNotFoundError(f"Product pattern '{pattern_ref}' missing system.yaml")

        # Version check
        with open(meta_path) as f:
            meta = yaml.safe_load(f)
        pinned_version = product_spec.get("version")
        if pinned_version and meta["pattern"]["version"] != pinned_version:
            raise ValueError(
                f"Product pattern '{pattern_ref}' version mismatch: "
                f"manifest pins {pinned_version}, pattern has {meta['pattern']['version']}"
            )

        with open(system_path) as f:
            sys_data = yaml.safe_load(f)

        # Contexts — merge _context.yaml (if present) with inline contexts from system.yaml
        # Inline contexts are needed because containers reference them via context_id
        ctx_from_dir, ctx_rels_from_dir = _load_pattern_contexts(pattern_dir, prefix)
        inline_contexts = _prefix_ids_in_list(
            sys_data.get("contexts", []), prefix
        )
        # Merge: start with inline, add any from _context.yaml that aren't duplicates
        inline_ids = {c["id"] for c in inline_contexts if "id" in c}
        contexts = list(inline_contexts)
        for ctx in ctx_from_dir:
            if ctx.get("id") not in inline_ids:
                contexts.append(ctx)
        # Apply context_name override
        if product_spec.get("context_name") and contexts:
            contexts[0]["name"] = product_spec["context_name"]

        # Containers
        containers = _prefix_ids_in_list(
            sys_data.get("containers", []), prefix,
            ref_fields=["context_id"]
        )

        # Components — need to prefix container_id and listener IDs
        components = []
        for comp in sys_data.get("components", []):
            c = copy.deepcopy(comp)
            c["id"] = _prefix_id(c["id"], prefix)
            if "container_id" in c:
                c["container_id"] = _prefix_id(c["container_id"], prefix)
            # Prefix listener IDs
            for listener in c.get("listeners", []):
                listener["id"] = _prefix_id(listener["id"], prefix)
            components.append(c)

        # Component relationships
        relationships = _prefix_ids_in_list(
            sys_data.get("component_relationships", []), prefix,
            ref_fields=["source_component", "target_component", "target_listener_ref"]
        )

        # Container relationships
        ctr_relationships = _prefix_ids_in_list(
            sys_data.get("container_relationships", []), prefix,
            ref_fields=["source_container", "target_container"]
        )

        # External systems, data entities, trust boundaries
        ext_systems = _prefix_ids_in_list(
            sys_data.get("external_systems", []), prefix
        )
        data_ents = _prefix_ids_in_list(
            sys_data.get("data_entities", []), prefix
        )
        trust_bounds = _prefix_ids_in_list(
            sys_data.get("trust_boundaries", []), prefix,
            ref_fields=["source_zone", "target_zone"]
        )

        # Apply overrides
        containers = _apply_overrides(containers, overrides, prefix)
        components = _apply_overrides(components, overrides, prefix)

        # Load optional networks.yaml from product pattern (unified patterns)
        product_networks_path = pattern_dir / "networks.yaml"
        if product_networks_path.exists():
            with open(product_networks_path) as f:
                prod_net_data = yaml.safe_load(f) or {}
            # Don't prefix allowed_ingress/egress_zones — those reference zones
            # from OTHER patterns whose final IDs depend on the other pattern's
            # id_prefix. Cross-pattern zone links should use cross_network_links
            # in the manifest instead.
            prod_zones = _prefix_ids_in_list(
                prod_net_data.get("network_zones", []), prefix,
                ref_fields=[]
            )
            prod_resources = _prefix_ids_in_list(
                prod_net_data.get("infrastructure_resources", []), prefix,
                ref_fields=["zone_id"]
            )
            prod_zones = _apply_overrides(prod_zones, overrides, prefix)
            prod_resources = _apply_overrides(prod_resources, overrides, prefix)
            all_product_zones.extend(prod_zones)
            all_product_resources.extend(prod_resources)

        all_contexts.extend(contexts)
        all_context_relationships.extend(ctx_rels_from_dir)
        all_containers.extend(containers)
        all_components.extend(components)
        all_relationships.extend(relationships)
        all_container_relationships.extend(ctr_relationships)
        all_external_systems.extend(ext_systems)
        all_data_entities.extend(data_ents)
        all_trust_boundaries.extend(trust_bounds)

    # Add cross-product relationships from manifest (with referential integrity check)
    all_comp_ids = {c["id"] for c in all_components}
    for rel in manifest.get("cross_product_relationships", []):
        for field in ("source_component", "target_component"):
            ref = rel.get(field)
            if ref and ref not in all_comp_ids:
                raise ValueError(
                    f"cross_product_relationships: {field} '{ref}' not found "
                    f"in composed components"
                )
        all_relationships.append(copy.deepcopy(rel))

    # Merge network pattern contexts into the system (if any)
    # Network contexts come from compose_network's _contexts key
    # They are injected via compose() after both compose_network and compose_system run

    # Build composed system
    composed = {
        "metadata": {
            "name": manifest["name"],
            "description": manifest.get("description", ""),
            "owner": "composed-deployment",
            "status": manifest.get("status", "proposed"),
        },
        "contexts": all_contexts,
        "containers": all_containers,
        "components": all_components,
        "component_relationships": all_relationships,
    }

    if all_context_relationships:
        composed["context_relationships"] = all_context_relationships
    if all_container_relationships:
        composed["container_relationships"] = all_container_relationships
    if all_external_systems:
        composed["external_systems"] = all_external_systems
    if all_data_entities:
        composed["data_entities"] = all_data_entities
    if all_trust_boundaries:
        composed["trust_boundaries"] = all_trust_boundaries

    # Stash product-contributed zones/resources for merging into networks
    if all_product_zones:
        composed["_product_zones"] = all_product_zones
    if all_product_resources:
        composed["_product_resources"] = all_product_resources

    return composed


def compose_deployment(manifest: dict) -> dict:
    """Generate deployment YAML from manifest placements.

    Structural fields (container_id, replicas) stay in deployment.yaml.
    Security fields (runtime_user, read_only_filesystem, etc.) are separated
    by _build_deployment_security_stub() into deployment-security.yaml.
    """
    deployment = {
        "deployment_metadata": {
            "id": manifest["id"],
            "name": manifest["name"],
            "environment": manifest["environment"],
            "status": manifest.get("status", "proposed"),
        },
    }

    if manifest.get("region"):
        deployment["deployment_metadata"]["region"] = manifest["region"]
    # cloud_provider stays in deployment_metadata for backward compat but is
    # also copied to deployment_posture in the security stub

    # Build zone placements from manifest — structural fields only
    placements = manifest.get("placements", [])
    if placements:
        zone_map: dict[str, list[dict]] = {}
        for p in placements:
            zone_ref = p["zone_ref"]
            if zone_ref not in zone_map:
                zone_map[zone_ref] = []
            container_entry: dict = {"container_id": p["container_ref"]}
            # Only structural fields in base deployment
            if "replicas" in p:
                container_entry["replicas"] = p["replicas"]
            zone_map[zone_ref].append(container_entry)

        deployment["zone_placements"] = [
            {"zone_id": zone_id, "containers": ctrs}
            for zone_id, ctrs in zone_map.items()
        ]

    return deployment


def _build_system_security_stub(manifest: dict, system: dict) -> dict:
    """Build system-security.yaml stub from composed data."""
    stub: dict = {
        "security_metadata": {
            "system_ref": manifest.get("name", ""),
        },
        "component_security": [],
    }
    # Move data_entities and trust_boundaries to security stub if present
    if system.get("data_entities"):
        stub["data_entities"] = system.pop("data_entities")
    if system.get("trust_boundaries"):
        stub["trust_boundaries"] = system.pop("trust_boundaries")
    return stub


def _build_networks_security_stub(manifest: dict, networks: dict) -> dict:
    """Build networks-security.yaml stub from composed data."""
    # Build composite networks_ref from all network pattern refs
    try:
        net_specs = _normalize_network_specs(manifest)
        net_refs = [f"{s['id_prefix']}:{s['pattern_ref']}" for s in net_specs]
        networks_ref = ", ".join(net_refs) if len(net_refs) > 1 else net_refs[0]
    except (ValueError, IndexError):
        networks_ref = ""
    stub: dict = {
        "network_security_metadata": {
            "networks_ref": networks_ref,
        },
        "zone_security": [],
    }
    # Move infrastructure_resources to security stub if present
    if networks.get("infrastructure_resources"):
        stub["infrastructure_resources"] = networks.pop("infrastructure_resources")
    return stub


def _build_deployment_security_stub(manifest: dict, deployment: dict) -> dict:
    """Build deployment-security.yaml stub from composed data.

    Extracts runtime security fields from manifest placements into
    container_security entries keyed by container_id + zone_id.
    Also populates deployment_posture from manifest-level fields.
    """
    _SECURITY_FIELDS = (
        "runtime_user", "read_only_filesystem", "resource_limits_set",
        "network_policy_enforced", "image_signed", "image_registry",
        "image_tag", "image_digest", "vulnerability_scan_date",
    )

    stub: dict = {
        "deployment_security_metadata": {
            "deployment_ref": manifest.get("id", ""),
        },
    }

    # Build deployment_posture from manifest-level security fields
    posture: dict = {}
    if manifest.get("cloud_provider"):
        posture["cloud_provider"] = manifest["cloud_provider"]
    if manifest.get("shared_responsibility_model"):
        posture["shared_responsibility_model"] = manifest["shared_responsibility_model"]
    if manifest.get("tenant_isolation"):
        posture["tenant_isolation"] = manifest["tenant_isolation"]
    if manifest.get("data_residency_region"):
        posture["data_residency_region"] = manifest["data_residency_region"]
    if manifest.get("data_residency_required") is not None:
        posture["data_residency_required"] = manifest["data_residency_required"]
    if posture:
        stub["deployment_posture"] = posture

    # Extract container-level security fields from manifest placements
    container_sec: list[dict] = []
    for p in manifest.get("placements", []):
        sec_entry: dict = {}
        for field in _SECURITY_FIELDS:
            if field in p:
                sec_entry[field] = p[field]
        if sec_entry:
            sec_entry["container_id"] = p["container_ref"]
            sec_entry["zone_id"] = p["zone_ref"]
            container_sec.append(sec_entry)

    stub["container_security"] = container_sec
    return stub


def _detect_circular_refs(manifest: dict) -> list[str]:
    """Detect circular ID references in the composed manifest.

    Checks that container→context, component→container, and relationship
    source→target references don't form cycles.  Returns a list of error
    strings (empty = no cycles).
    """
    errors: list[str] = []

    # Check for duplicate id_prefix values across ALL patterns (network + product)
    prefixes = [p["id_prefix"] for p in manifest.get("products", [])]
    try:
        net_specs = _normalize_network_specs(manifest)
        prefixes.extend(s["id_prefix"] for s in net_specs)
    except ValueError:
        pass  # Will be caught later by compose_networks
    seen = set()
    for p in prefixes:
        if p in seen:
            errors.append(f"Duplicate id_prefix '{p}' would cause ID collisions")
        seen.add(p)

    # Check cross_product_relationships for self-referencing cycles
    for i, rel in enumerate(manifest.get("cross_product_relationships", [])):
        src = rel.get("source_component", "")
        tgt = rel.get("target_component", "")
        if src and tgt and src == tgt:
            errors.append(
                f"cross_product_relationships[{i}]: self-referencing "
                f"relationship '{src}' → '{tgt}'"
            )

    return errors


def _load_pattern_dataflows(pattern_dir: Path, prefix: str) -> list[dict]:
    """Load app-dataflows.yaml and human-dataflows.yaml from a pattern, prefix IDs."""
    all_flows = []
    for fname in ("app-dataflows.yaml", "human-dataflows.yaml"):
        fpath = pattern_dir / fname
        if not fpath.exists():
            continue
        try:
            with open(fpath) as f:
                data = yaml.safe_load(f) or {}
        except yaml.YAMLError as e:
            raise ValueError(f"Cannot parse {fpath}: {e}") from e
        flows = data.get("dataflows", [])
        prefixed = _prefix_ids_in_list(
            flows, prefix,
            ref_fields=["source_zone", "target_zone",
                         "source_component", "target_component",
                         "target_listener_ref"]
        )
        # Tag each flow with its audience source
        audience = data.get("dataflow_metadata", {}).get("audience", "")
        for flow in prefixed:
            flow.setdefault("_audience", audience)
            flow.setdefault("_source_pattern", prefix)
        all_flows.extend(prefixed)
    return all_flows


def compose(manifest_path: Path, dry_run: bool = False,
            validate: bool = False) -> dict:
    """Main composition pipeline."""
    with open(manifest_path) as f:
        raw = yaml.safe_load(f)

    manifest = raw.get("manifest")
    if not manifest:
        raise ValueError(f"Manifest file missing top-level 'manifest' key: {manifest_path}")

    # Pre-composition: detect circular references and ID collisions
    cycle_errors = _detect_circular_refs(manifest)
    if cycle_errors:
        raise ValueError(
            "Circular reference / ID collision detected:\n  "
            + "\n  ".join(cycle_errors)
        )

    # Compose
    networks = compose_networks(manifest)
    system = compose_system(manifest)
    deployment = compose_deployment(manifest)

    # Inject network pattern contexts into composed system
    net_contexts = networks.pop("_contexts", [])
    net_ctx_rels = networks.pop("_context_relationships", [])
    if net_contexts:
        system["contexts"] = net_contexts + system.get("contexts", [])
    if net_ctx_rels:
        existing_ctx_rels = system.get("context_relationships", [])
        system["context_relationships"] = net_ctx_rels + existing_ctx_rels

    # Inject network pattern system data (containers/components from network patterns)
    net_system_data = networks.pop("_network_system_data", [])
    for net_prefix, sys_data in net_system_data:
        net_containers = _prefix_ids_in_list(
            sys_data.get("containers", []), net_prefix,
            ref_fields=["context_id"]
        )
        system["containers"] = system.get("containers", []) + net_containers
        # Components from network pattern system.yaml
        for comp in sys_data.get("components", []):
            c = copy.deepcopy(comp)
            c["id"] = _prefix_id(c["id"], net_prefix)
            if "container_id" in c:
                c["container_id"] = _prefix_id(c["container_id"], net_prefix)
            for listener in c.get("listeners", []):
                listener["id"] = _prefix_id(listener["id"], net_prefix)
            system.setdefault("components", []).append(c)
        # Relationships from network pattern system.yaml
        net_rels = _prefix_ids_in_list(
            sys_data.get("component_relationships", []), net_prefix,
            ref_fields=["source_component", "target_component", "target_listener_ref"]
        )
        system["component_relationships"] = system.get("component_relationships", []) + net_rels

    # Merge product-contributed zones into networks (unified patterns)
    product_zones = system.pop("_product_zones", [])
    product_resources = system.pop("_product_resources", [])
    if product_zones:
        existing_zone_ids = {z["id"] for z in networks.get("network_zones", [])}
        product_zone_ids = {z["id"] for z in product_zones}
        collisions = existing_zone_ids & product_zone_ids
        if collisions:
            raise ValueError(
                f"Zone ID collision between product and network patterns: {collisions}"
            )
        networks["network_zones"] = networks.get("network_zones", []) + product_zones
    if product_resources:
        networks.setdefault("infrastructure_resources", [])
        networks["infrastructure_resources"].extend(product_resources)

    # Apply cross_network_links AFTER product zones are merged so links
    # can reference both network-pattern and product-contributed zones
    _apply_cross_network_links(
        networks.get("network_zones", []),
        manifest.get("cross_network_links", [])
    )

    # Load and merge dataflows from all patterns
    all_dataflows = []
    try:
        net_specs = _normalize_network_specs(manifest)
    except ValueError:
        net_specs = []
    for net_spec in net_specs:
        pattern_dir = _find_pattern_dir(net_spec["pattern_ref"], "network")
        if pattern_dir:
            all_dataflows.extend(_load_pattern_dataflows(pattern_dir, net_spec["id_prefix"]))
    for prod_spec in manifest.get("products", []):
        pattern_dir = _find_pattern_dir(prod_spec["pattern_ref"], "product")
        if pattern_dir:
            all_dataflows.extend(_load_pattern_dataflows(pattern_dir, prod_spec["id_prefix"]))

    # Validate dataflow references (warnings, not errors — flows may reference externals)
    dataflow_warnings = []
    if all_dataflows:
        zone_ids = {z["id"] for z in networks.get("network_zones", [])}
        comp_ids = {c["id"] for c in system.get("components", [])}
        for flow in all_dataflows:
            flow_id = flow.get("id", "<unknown>")
            for field, valid_set in [("source_zone", zone_ids),
                                      ("target_zone", zone_ids),
                                      ("source_component", comp_ids),
                                      ("target_component", comp_ids)]:
                if field in flow and flow[field] not in valid_set:
                    dataflow_warnings.append(
                        f"Dataflow '{flow_id}': {field} '{flow[field]}' "
                        f"not found in composed output"
                    )

    # Validate infrastructure_resources zone_id refs
    zone_ids_all = {z["id"] for z in networks.get("network_zones", [])}
    for res in networks.get("infrastructure_resources", []):
        zid = res.get("zone_id")
        if zid and zid not in zone_ids_all:
            dataflow_warnings.append(
                f"Infrastructure resource '{res.get('id', '?')}': "
                f"zone_id '{zid}' not found in composed zones"
            )

    # Build security overlay stubs from composed data
    system_security = _build_system_security_stub(manifest, system)
    networks_security = _build_networks_security_stub(manifest, networks)
    deployment_security = _build_deployment_security_stub(manifest, deployment)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        rel_manifest = str(manifest_path.relative_to(PROJECT_ROOT))
    except ValueError:
        rel_manifest = str(manifest_path)
    header = GENERATED_HEADER.format(
        manifest_path=rel_manifest,
        timestamp=timestamp,
    )

    output_dir = manifest_path.parent

    result = {
        "valid": True,
        "networks": networks,
        "system": system,
        "deployment": deployment,
        "dataflows": all_dataflows,
        "output_dir": str(output_dir),
        "errors": [],
        "warnings": dataflow_warnings,
    }

    if dry_run:
        print(json.dumps({
            "dry_run": True,
            "valid": True,
            "networks_zones_count": len(networks.get("network_zones", [])),
            "system_contexts_count": len(system.get("contexts", [])),
            "system_containers_count": len(system.get("containers", [])),
            "system_components_count": len(system.get("components", [])),
            "system_relationships_count": len(system.get("component_relationships", [])),
            "deployment_placements_count": len(deployment.get("zone_placements", [])),
            "security_infra_resources_count": len(networks_security.get("infrastructure_resources", [])),
            "security_data_entities_count": len(system_security.get("data_entities", [])),
            "security_trust_boundaries_count": len(system_security.get("trust_boundaries", [])),
            "security_container_security_count": len(deployment_security.get("container_security", [])),
            "security_has_deployment_posture": "deployment_posture" in deployment_security,
            "dataflows_count": len(all_dataflows),
            "output_dir": str(output_dir),
        }, indent=2))
        return result

    # Write dataflows if any were loaded
    files_written = []
    if all_dataflows:
        # Split by audience for separate output files
        app_flows = [f for f in all_dataflows if f.get("_audience") == "application"]
        human_flows = [f for f in all_dataflows if f.get("_audience") == "human"]
        hybrid_flows = [f for f in all_dataflows if f.get("_audience") not in ("application", "human")]
        # Strip internal tags before writing
        for flows in (app_flows, human_flows, hybrid_flows):
            for f in flows:
                f.pop("_audience", None)
                f.pop("_source_pattern", None)
        if app_flows:
            df_out = {"dataflow_metadata": {"audience": "application"}, "dataflows": app_flows}
            out_path = output_dir / "app-dataflows.yaml"
            with open(out_path, "w") as fh:
                fh.write(header)
                yaml.dump(df_out, fh, default_flow_style=False, sort_keys=False, allow_unicode=True)
            files_written.append(str(out_path))
        if human_flows:
            df_out = {"dataflow_metadata": {"audience": "human"}, "dataflows": human_flows}
            out_path = output_dir / "human-dataflows.yaml"
            with open(out_path, "w") as fh:
                fh.write(header)
                yaml.dump(df_out, fh, default_flow_style=False, sort_keys=False, allow_unicode=True)
            files_written.append(str(out_path))
        if hybrid_flows:
            df_out = {"dataflow_metadata": {"audience": "hybrid"}, "dataflows": hybrid_flows}
            out_path = output_dir / "hybrid-dataflows.yaml"
            with open(out_path, "w") as fh:
                fh.write(header)
                yaml.dump(df_out, fh, default_flow_style=False, sort_keys=False, allow_unicode=True)
            files_written.append(str(out_path))

    # Write output files (base + security overlays)
    for fname, data in [("networks.yaml", networks),
                        ("system.yaml", system),
                        ("deployment.yaml", deployment),
                        ("system-security.yaml", system_security),
                        ("networks-security.yaml", networks_security),
                        ("deployment-security.yaml", deployment_security)]:
        out_path = output_dir / fname
        with open(out_path, "w") as f:
            f.write(header)
            yaml.dump(data, f, default_flow_style=False, sort_keys=False,
                      allow_unicode=True)

    # Create diagrams/ directory with _index.yaml stub and custom/ subdirectory
    diagrams_dir = output_dir / "diagrams"
    diagrams_dir.mkdir(exist_ok=True)
    custom_dir = diagrams_dir / "custom"
    custom_dir.mkdir(exist_ok=True)

    index_path = diagrams_dir / "_index.yaml"
    if not index_path.exists():
        index_data = {
            "generated_at": timestamp,
            "scope_type": "deployment",
            "scope_id": manifest["id"],
            "source_manifest": "manifest.yaml",
            "diagrams": [],
            "custom_diagrams": [],
        }
        with open(index_path, "w") as f:
            f.write(header)
            yaml.dump(index_data, f, default_flow_style=False,
                      sort_keys=False, allow_unicode=True)

    # Validate composed output
    if validate:
        try:
            sys.path.insert(0, str(PROJECT_ROOT / "tools"))
            from validate import validate as run_validate
            val_result = run_validate(
                str(output_dir / "system.yaml"),
                str(output_dir / "networks.yaml"),
            )
            result["errors"] = val_result.get("errors", [])
            result["warnings"] = val_result.get("warnings", [])
            result["valid"] = val_result.get("valid", True)
        except Exception as e:
            result["warnings"].append(f"Validation skipped: {e}")

    print(json.dumps({
        "valid": result["valid"],
        "errors": result["errors"],
        "warnings": result["warnings"],
        "files_written": [
            str(output_dir / "networks.yaml"),
            str(output_dir / "system.yaml"),
            str(output_dir / "deployment.yaml"),
            str(output_dir / "system-security.yaml"),
            str(output_dir / "networks-security.yaml"),
            str(output_dir / "deployment-security.yaml"),
            str(output_dir / "diagrams" / "_index.yaml"),
        ] + files_written,
    }, indent=2))

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Compose deployment from manifest + patterns")
    parser.add_argument("manifest", type=Path,
                        help="Path to manifest.yaml")
    parser.add_argument("--validate", action="store_true",
                        help="Validate composed output against schemas")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print composition summary without writing files")
    args = parser.parse_args()

    if not args.manifest.exists():
        print(json.dumps({
            "valid": False,
            "errors": [f"Manifest not found: {args.manifest}"],
        }))
        sys.exit(1)

    try:
        result = compose(args.manifest, dry_run=args.dry_run,
                         validate=args.validate)
        sys.exit(0 if result["valid"] else 1)
    except Exception as e:
        print(json.dumps({
            "valid": False,
            "errors": [str(e)],
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()
